---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: molecule-ubuntu
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2404}-ansible:latest"
    published_ports:
      - 0.0.0.0:873:873/tcp
    exposed_ports:
      - 873/tcp

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      molecule-ubuntu:
        ansible_user: root


verifier:
  name: ansible


lint: |
  set -e
  yamllint .
  ansible-lint .
