---
- name: Fail if molecule group is missing
  hosts: localhost
  vars:
    molecule_inventory:
      all:
        hosts: {}
        molecule: {}
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Include test-rsync_server
      ansible.legacy.include_role:
        name: testrsync_server
