---
name: CI

'on':
  pull_request:
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: "0 7 * * 0"

defaults:
  run:
    working-directory: 'bulch.rsync_server'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4.1.6
        with:
          path: 'bulch.rsync_server'

      - name: Set up Python 3.
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Install molecule deps
        run: |
          ansible-galaxy install -r molecule/default/requirements.yml

      - name: Install root deps
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Lint code yamllint.
        run: |
          yamllint -c=.yamllint .

      - name: Run ansible-lint
        run: |
          exit_code=0
          expected_exit_code=0
          ansible-lint . || exit_code=$?
          if [ "$exit_code" != "$expected_exit_code" ]; then echo "Command failed: got '$exit_code', expected '$expected_exit_code'"; exit 1; fi

  molecule:
    name: Molecule
    needs: lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        distro:
          - ubuntu2404
          - ubuntu2204
          - ubuntu2004
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4.1.6
        with:
          path: 'bulch.rsync_server'

      - name: Set up Python 3.
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install -r requirements.txt

      - name: Createt vault
        run: echo "qwerty" > .vault_password

      - name: Run Molecule tests.
        run: molecule --debug test --all
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
